---
title: "R Notebook"
output: html_notebook
Author: "Akshay Kale"
---


loading libraries..
```{r}
library(lattice)
library(ISLR)
library(MASS)
library(caret)
library(tidyverse)
library(plyr)
```



```{r}
nbi <- read.csv('nbi_timerseries.csv')
head(nbi)
```
```{r}
nbi$Maintainer <- as.factor((nbi$Maintainer))
nbi$State.Code <- as.factor((nbi$State.Code))
nbi$Owner <- as.factor((nbi$Owner))
nbi$Material <- as.factor((nbi$Material))
nbi$Structure.Type <- as.factor((nbi$Structure.Type))

nbi$Material = mapvalues(nbi$Material, 
                from = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "-1", "0"),
                 to = c("Concrete", "Concrete Continuous", "Steel", "Steel Continuous", "Prestressed Concrete", "Prestressed Concrete Continuous", "Wood or Timber", "Masonry", "Aluminium", "NA", "Other"))
head(nbi)
```


```{r}
index = createDataPartition(y=nbi$Category, p=0.7, list=FALSE)

train.set = nbi[index,]
test.set = nbi[-index,]

dim(train.set)
```
```{r}
dim(test.set)
```

# Method Section:

## Interest:
    Primary goal is to understand
    1. Validating the paramenters from the previous research and their importance
    2. We can probably using the
    
    

```{r}
grid <- expand.grid(cp=seq(0,1,0.01))

nbi.tree = train(Category ~ State.Code + Age_L + Material + ADT.Category +  ADTT.Category + Maintainer + Structure.Type,
                 data = train.set,
                 method = "rpart",
                 trControl = trainControl(method = "cv"),
                 tuneLength = 10,
                 tuneGrid = grid)



```

```{r}
nbi.tree
```


```{r}
# Variable Importance
varImp(nbi.tree)
```

```{r}
suppressMessages(library(rattle))

fancyRpartPlot(nbi.tree$finalModel)
```

```{r}
nbi.pred = predict(nbi.tree, newdata = test.set)
```
```{r}
table(nbi.pred, test.set$Category)
error.rate = round(mean(nbi.pred != test.set$Category), 2)
error.rate
```

```{r}
confusionMatrix(nbi.pred, test.set$Category)
```

```{r}


```

What do you
  

